services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
        restart: unless-stopped
        volumes:
            - ./prometheus:/etc/prometheus:ro
            - prom_data:/prometheus:rw
        networks:
            back-tier:
                alias:
                    - database
            admin:
                alias:
                    - mysql
            undefined:
                alias:
                    - unknown
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - target: 80
              host_ip: 127.0.0.1
              published: 8080
              protocol: tcp
              mode: host
            - target: 8000
              host_ip: 127.0.0.1
              published: 8000-9000
              protocol: tcp
              mode: host
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=grafana
        volumes:
            - type: volume
              source: ./grafana
              target: /etc/grafana/provisioning/datasources
              read_only: true
              volume:
                - nocopy: true
        networks:
            - front-tier:
                alias:
                    - ui
            - back-tier:
    datadog:
        image: datadog/datadog
volumes:
    prom_data:
networks:
    front-tier:
        external: true
        name: front-end-net
        driver: overlay
    back-tier:
        name: back-end-net
        internal: true
        labels:
            - "com.example.description=Financial transaction network"
            - "com.example.department=Finance"
            - "com.example-label-with-empty-value"
    admin:
        attachable: true
        enable_ipv6: false
        labels:
            com.example.description: "Financial transaction network"
            com.example.department: "Finance"
            com.example.label-with-empty-value: ""
