version: '3.8'

services:
  infragenie:
    image: infragenie:latest
    container_name: infragenie-container
    ports:
      - "8080:8080" # Expose port 8080 or customize as needed
    environment:
      - ENV=development
      - DEBUG=true
    volumes:
      - ./infragenie-config:/app/config # Mount config files or directories
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: infragenie-db
    environment:
      POSTGRES_USER: infragenie
      POSTGRES_PASSWORD: infragenie_password
      POSTGRES_DB: infragenie_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
