version: '2'
services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml2

  app:
    container_name: django-app
    restart: always
    volumes:
      - ./infra_crawler:/infra_crawler
      - static_volume:/infra_crawler/app/staticfiles

volumes:
  static_volume:
