on: [push]

# Write permissions are required to commit the diagram to the repository
permissions:
  contents: write

jobs:
  update-architecture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug GitHub Action
        run: echo "Testing access to infragenie-ghaction"

      - name: Run infragenie action
        uses: Rikenunes8/infragenie-ghaction@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
